### ISSUE TITLE
Broken due to processor sort line change

### ISSUE THREAD

**Issue by sheldonhull** [abhimanyu003/sttr#17]
@abhimanyu003 

> go/pkg/mod/github.com/abhimanyu003/sttr@v0.2.1/cmd/processor_sort-lines.go:40:25

This just happened in the last hour when I was repulling it into a new project. 

This version works: `go install github.com/abhimanyu003/sttr@e5600168e954fbe603cba134226874b1e81c297a`, everything after this fails. 

Suggest that might be a good github action for post-merge to flag an install failure

**Comment by abhimanyu003** [comment]
Hello @sheldonhull thanks for reporting, I tagged with the new version.
> I will update githooks so that it will not happen again.

Update it on go proxy as well https://pkg.go.dev/github.com/abhimanyu003/sttr

Now you will be able to do.

```
go get github.com/abhimanyu003/sttr@v0.2.2
```

Please let me know if you face any more issues.
