### ISSUE TITLE
Support for macOS with M1 chips.

### ISSUE THREAD

**Issue by hoanghun** [abhimanyu003/sttr#24]
Currently unable to follow the installation guide for installation on macOS 12.1 with Apple M1 because of the following error:

```
Error: Invalid formula: /opt/homebrew/Library/Taps/abhimanyu003/homebrew-sttr/Formula/sttr.rb
formulae require at least a URL
Error: Cannot tap abhimanyu003/sttr: invalid syntax in tap!
```

I suppose the error stems from this part in the formulae which seems to support only Intel chips?:

```
on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abhimanyu003/sttr/releases/download/v0.2.11/sttr_0.2.11_darwin_amd64.tar.gz"
      sha256 "37f720259894838ccbebf2d2491305f05be47daf3f2a509b2f0b5b06a3f1811f"

      def install
        bin.install "sttr"
      end
    end
  end
```

**Comment by abhimanyu003** [comment]
Hello @hoanghun 
Many thanks for your report.

I have updated support for M1 chips, also update the brew.

Can you please give it a try and let me know.

**Comment by hoanghun** [comment]
I successfully installed via Homebrew. Thank you for the fast fix.
