### ISSUE TITLE
why not perl?

### ISSUE THREAD

**Issue by bugsn4x** [abhimanyu003/sttr#26]

**Comment by abhimanyu003** [comment]
Hello @bugsn4x 
Can you please add details why perl and not GO?

**Comment by bugsn4x** [comment]
No, I mean why invent a CLI string transformer tool when the Practical Extraction and Report Language exists?

**Comment by abhimanyu003** [comment]
Hello, I have to close this as an issue as it's just personal choice and preferences.
The reasons I have chosen GOLang is are.

* It's cross-platform. I wanted this to work almost anywhere just from binary, without installing language on the system.
* Echosystem and community are quite rich and supportive.
* I personally don't have much exposure to PERL.
* There are many great TUI / CLI libraries for GO.

So for some of these reasons I have chosen GO.

**Comment by bugsn4x** [comment]
No, I mean there is already many tools for string manipulation. We don't have to write yet another one.

* awk
* sh
* perl
