### ISSUE TITLE
suggestion：add result to clipboard.

### ISSUE THREAD

**Issue by Developer27149** [abhimanyu003/sttr#29]

**Comment by abhimanyu003** [comment]
Hello @Developer27149 
Thanks so much for the suggestion.

We have two use cases here:
* Auto copy to clipboard when using TUI mode. ( not everyone will like auto-copy, so maybe I will flag this as well. )
* Provide a flag when using CLI version

**Comment by Developer27149** [comment]
@abhimanyu003 Yes.I agree with you.

**Comment by Alpensin** [comment]
For unix usage it is handy to use typical pipes in cli mode. Like that in mac
`sttr  base64-encode asdasdassaddas | pbcopy`

**Comment by Developer27149** [comment]
Hello @abhimanyu003 @Alpensin 
Thinking about it now, lazy people like me may tend to write as few commands as possible, whether it's CLI Options  or pbcopy  😂​
not bad? For example, read the  config  directory under the user's home directory, and there is a  .sttrrc  configuration file inside, and the user can freely control whether to automatically copy to the clipboard.

**Comment by abhimanyu003** [comment]
hey @Developer27149 i'm actually thinking about it `.sttrrc` file seems like good suggestion. I will think about this more.
