### ISSUE TITLE
possibility of making the json escape function not sorting the input?

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [abhimanyu003/sttr#30]
It would be useful to have a extra flag to make sure the output keys is not sorted.
Since sometimes,I need to feed it to other cli tool or onlt want sttr to just escape it directly will keeping it,unsorted*.

**Comment by abhimanyu003** [comment]
Hello @RESDXChgfore9hing 
Thanks so much for reporting this issue, looks like I have to figure out some solution for this.
There is also a bug report open in go internal repo **[encoding/json: no way to preserve the order of map keys](https://github.com/golang/go/issues/27179)**

In **sttr** code can be found here **[processors/json.go#L315](https://github.com/abhimanyu003/sttr/blob/main/processors/json.go#L315)**

**Comment by abhimanyu003** [comment]
Hello @RESDXChgfore9hing 
This is fixed in the latest commit https://github.com/abhimanyu003/sttr/commit/ef78637820bd25a27a62c6b4de467b026fe59b88
You can get the specific commit using

```
go install github.com/abhimanyu003/sttr@ef78637820bd25a27a62c6b4de467b026fe59b88
```

I will do a tagged release this week. Have to look into few things at other area as well.

**Comment by RESDXChgfore9hing** [comment]
damn thats fast,looks good. will wait for release at weekend

**Comment by abhimanyu003** [comment]
A new tagged release version is out now.
Thanks again so much for reporting this issue.

https://github.com/abhimanyu003/sttr/releases/tag/v0.2.14
