### ISSUE TITLE
enhancement: show sub command hints in menu

### ISSUE THREAD

**Issue by coolaj86** [abhimanyu003/sttr#34]
Current:

```text
   Ascii85 / Base85 Decoding
   Decode your text to Ascii85 ( Base85 ) text

   Ascii85 / Base85 Encoding
   Encode your text to Ascii85 ( Base85 )

   Base32 Decode
   Decode your base32 text

   Base32 Encoding
   Encode your text to Base32

   Base64 Decode
   Decode your base64 text

   Base64 Encoding
   Encode your text to Base64
```

Desired:

```text
   Ascii85 / Base85 Decoding (ascii85-decode)
   Decode your text to Ascii85 ( Base85 ) text

   Ascii85 / Base85 Encoding (ascii85-encode)
   Encode your text to Ascii85 ( Base85 )

   Base32 Decode (base32-decode)
   Decode your base32 text

   ...
```

Or something like that.

**Comment by abhimanyu003** [comment]
Thanks so much, this is a great idea. I'm looking at possible solutions for this

**Comment by abhimanyu003** [comment]
Thanks so much again for the suggestion.

This is now added in commit 9aa2088d404c29e3d1f059b8b7713f2d93290720 

**Will do a tagged release soon.**

Screenshot:

<img width="604" alt="image" src="https://user-images.githubusercontent.com/265913/230332314-321adf2a-617f-43e7-b849-eee6c6a7d865.png">

If you think there is something, feel free to open this issue again 🎉
