### ISSUE TITLE
enhancement: sub command usage hints - single arg or ctrl+d

### ISSUE THREAD

**Issue by coolaj86** [abhimanyu003/sttr#35]
## single string arg

I can see why it should only accept a single string for many of these commands, but it would be nice to update the help message to show that.

```sh
sttr snake Hello World!
```

```text
Error: accepts at most 1 arg(s), received 2
Usage:
  sttr snake [flags] [string] <===========

Flags:
  -h, --help   help for snake
```

```sh
sttr snake 'Hello World!'
```

```text
hello_world!
```

## ctrl+d

Likewise, it would be nice if either the same double-empty-newline rule applied for stdin input, or if a message about <kbd>Ctrl ⌃</kbd> + <kbd>d</kbd>  was printed.

```sh
sttr snake
Hello World!





<ctrl+d>
```

```text
hello_world!
```

```sh
sttr snake
Press <ctrl+d> to end <=========
Hello World!
```

```text
hello_world!
```

**Comment by abhimanyu003** [comment]
These are awesome suggestions, I'm looking into them. Thanks so much for putting them in.

**Comment by abhimanyu003** [comment]
This is updated in commit 78787de606d6d9d418fbb08dc166275e64758932
Let me know if you still think something can be done or is required.

<img width="383" alt="image" src="https://user-images.githubusercontent.com/265913/230549599-721b5c81-1c54-4de3-8328-9196a04fc699.png">

**Comment by abhimanyu003** [comment]
double-empty-newline rule is also added to CLI 4ce96995b90efb3c6baf6e4b0852636b154989fe

![out](https://user-images.githubusercontent.com/265913/230595533-783ee590-54f5-46aa-9820-7eaa77567134.gif)

**Comment by abhimanyu003** [comment]
r
