### ISSUE TITLE
Error when attempting to install the application through curl

### ISSUE THREAD

**Issue by roopeshsn** [abhimanyu003/sttr#37]
Ran the command `curl -sfL https://raw.githubusercontent.com/abhimanyu003/sttr/main/install.sh | sh` from the bin directory,

```
install: cannot create regular file '/usr/local/bin/sttr': Permission denied
```
Tried with sudo too.

What's the cause of the error and how to rectify it?

**Comment by abhimanyu003** [comment]
Hello @roopeshsn thanks so much for reaching out.

Can you please try this once? 

```
curl -s https://raw.githubusercontent.com/abhimanyu003/sttr/master/install.sh | sudo bash
```

You can also use webi, after install only needs to export the path.

```
curl -sS https://webi.sh/sttr | sh
```

Let me know.

**Comment by roopeshsn** [comment]
Why use Webi? After running the command  `curl -s https://raw.githubusercontent.com/abhimanyu003/sttr/master/install.sh | sudo bash` I am able to interact with the cli through `sttr` without exporting the path. As you said, why export the path through Webi? However to export the path, can't we do that by adding the line `export PATH="/usr/local/bin/sttr:$PATH"` in the install.sh?

**Comment by abhimanyu003** [comment]
Good to know this is working for you great.
```
curl -s https://raw.githubusercontent.com/abhimanyu003/sttr/master/install.sh | sudo bash
```

Webi is just another alternative installer like snap, aur etc. don't have to use `sudo` with it. ( It's optional )

I don't think we have to add it to `install.sh` as almost all users have `/usr/local/bin` path exported

**Comment by roopeshsn** [comment]
Alright, @abhimanyu003. Can I use the same command,
```
curl -s https://raw.githubusercontent.com/abhimanyu003/sttr/master/install.sh | sudo bash
```
in windows?

**Comment by abhimanyu003** [comment]
For Windows.
* Download the `tar` based on your Windows type.
* Extract the `tar`
* Move `sttr.exe` to `%SystemRoot%/System32` ( C:\Windows\System32 ) 
> You can also `sttr.exe` to any location you have in your system path

**Download Types**
* [sttr_0.2.18_windows_386.tar.gz](https://github.com/abhimanyu003/sttr/releases/download/v0.2.18/sttr_0.2.18_windows_386.tar.gz)
* [sttr_0.2.18_windows_amd64.tar.gz](https://github.com/abhimanyu003/sttr/releases/download/v0.2.18/sttr_0.2.18_windows_amd64.tar.gz)
* [sttr_0.2.18_windows_arm64.tar.gz](https://github.com/abhimanyu003/sttr/releases/download/v0.2.18/sttr_0.2.18_windows_arm64.tar.gz)

**Other Ways**

* Use `scoop`

```
scoop bucket add sttr https://github.com/abhimanyu003/scoop-bucket.git
scoop install sttr
```

* We are working on `choco` install and `powershell script`

Let me know your thoughts 💯
