### ISSUE TITLE
extract http links from plaintext or html

### ISSUE THREAD

**Issue by eadmaster** [abhimanyu003/sttr#38]
A common task with many use-cases.

**Comment by abhimanyu003** [comment]
Hello @eadmaster I will check how can I do this.
There are other things as well active/inactive links - domain etc.

**Comment by abhimanyu003** [comment]
Added in new release v.0.2.20, thanks so much for suggestion 
https://github.com/abhimanyu003/sttr/releases/tag/v0.2.20
