### ISSUE TITLE
[FEATURE-REQUEST] Add escape-single-quotes | escape-double-quotes

### ISSUE THREAD

**Issue by Azathothas** [abhimanyu003/sttr#41]
Hi,

It would be really nice to have a feature to escape single/double quotes.

I resort to using this online tool: https://tools.knowledgewalls.com/online-escape-single-or-double-quotes-from-string

I also found a python cli (sort of) : https://github.com/colinta/SublimeChangeQuotes

But, this feature in [sttr](https://github.com/abhimanyu003/sttr) itself would be very much appreciated.

**Comment by abhimanyu003** [comment]
This is a great suggestion, looks like I also need it for my daily use. 
I will try to pull this off as soon possible!!

**Comment by abhimanyu003** [comment]
This feature is added in master branch, I will test it for few days and then do a tag release.

**Comment by abhimanyu003** [comment]
Added in new release v.0.2.20, thanks so much for suggestion
https://github.com/abhimanyu003/sttr/releases/tag/v0.2.20
