### ISSUE TITLE
command bcrypt ignoring rounds-parameter

### ISSUE THREAD

**Issue by mueckl** [abhimanyu003/sttr#42]
I'm using version 0.2.20

It seems the bcrypt subcommand ignores the "Number of rounds"-parameter and uses always it's default value (=10)

```

user@host:~$ bin/sttr version
0.2.20

user@host:~$ time echo foobar | bin/sttr bcrypt 
$2a$10$HPs11TyDOG9iXxghmQF/qeLbIkqlsl5FmHIqe7GhJzmEs9lsH2lHy
real	0m0,121s
user	0m0,110s
sys	0m0,019s
user@host:~$ time echo foobar | bin/sttr bcrypt -r 12
$2a$10$RpRFWm9NGNe2/usl.1LYZuVmDVK.0xuAI0kvCCHE0PN.IT8K3jRK.
real	0m0,130s
user	0m0,112s
sys	0m0,026s

user@host:~$ bin/sttr help bcrypt
Get the Bcrypt hash of your text

Usage:
  sttr bcrypt [string] [flags]

Aliases:
  bcrypt, bcrypt-hash

Flags:
  -h, --help                    help for bcrypt
  -r, --number-of-rounds uint   Number of rounds (default 10)


```

**Comment by abhimanyu003** [comment]
Hello @mueckl 
Many thanks for your report and detailed explanation. 🙇 🙏 

This is fixed in https://github.com/abhimanyu003/sttr/commit/41d0dde4c01ef17c775cf793305b8660eea11c80

I will do a tag release soon.

**Comment by abhimanyu003** [comment]
Fixed in release https://github.com/abhimanyu003/sttr/releases/tag/v0.2.21

once again thanks so much.

**Comment by mueckl** [comment]
That was quick - Thank you - Looks good now
