### ISSUE TITLE
Was devtoys an inspiration for you?

### ISSUE THREAD

**Issue by ccoVeille** [abhimanyu003/sttr#52]
https://github.com/DevToys-app/DevToys

Are there any ideas you could find there for your tool of you didn't knew devtoys?

**Comment by abhimanyu003** [comment]
DevToys came into existence after `sttr` was first released or I started working on it. 
I can see DevToys it's a great tool as well, but with more UI focus :)

My goal here is to do directly in terminals or build pipelines + cross platform as much as possible.

**Comment by ccoVeille** [comment]
Thanks for your reply.

Maybe you could mention this in an "other tools", or "why this project" section in the README
