### ISSUE TITLE
Show an error if input is not correct JSON/Yaml

### ISSUE THREAD

**Issue by chaehni** [abhimanyu003/sttr#7]
Currently, the tool does not catch this and just returns without any output.

**Comment by fervic** [comment]
In addition to print an error, it should exit with non-zero code.

**Comment by abhimanyu003** [comment]
Hello @chaehni and @fervic 
Thanks for the reports, will update to have a proper error output.

**Comment by rverst** [comment]
I've submitted a PR for v0.2 that will resolve this issue.

**Comment by abhimanyu003** [comment]
This is now resolved with a new release, I'm closing this issue.
Thanks so much everyone.
